# version: "3"
# services:
#   commentRemoverJsUi:
#     build: .
#     ports:
#       - '8000:5000'
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     depends_on:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
